export const tags = [
    { name: 'axe', isToolPart: true },
    { name: 'chain', isToolPart: true },
    { name: 'chisel', isToolPart: true },
    { name: 'double_ingot', isToolPart: false },
    { name: 'double_sheet', isToolPart: false },
    { name: 'fishing_rod', isToolPart: true },
    { name: 'hammer', isToolPart: true },
    { name: 'hoe', isToolPart: true },
    { name: 'ingot', isToolPart: false },
    { name: 'javelin', isToolPart: true },
    { name: 'knife', isToolPart: true },
    { name: 'mace', isToolPart: true },
    { name: 'pickaxe', isToolPart: true },
    { name: 'propick', isToolPart: true },
    { name: 'rod', isToolPart: false },
    { name: 'saw', isToolPart: true },
    { name: 'scythe', isToolPart: true },
    { name: 'shears', isToolPart: true },
    { name: 'sheet', isToolPart: false },
    { name: 'shovel', isToolPart: true },
    { name: 'sword', isToolPart: true },
    { name: 'tuyere', isToolPart: true }
];
export const allToolParts = [
    { name: 'anvil', meltInto: 1400, useForgeTag: false, useDurability: false },
    { name: 'axe_head', meltInto: 100, useForgeTag: false, useDurability: false },
    { name: 'axe', meltInto: 100, useForgeTag: false, useDurability: true },
    { name: 'boots', meltInto: 400, useForgeTag: false, useDurability: true },
    { name: 'chain', meltInto: 6, useForgeTag: false, useDurability: false },
    { name: 'chestplate', meltInto: 800, useForgeTag: false, useDurability: true },
    { name: 'chisel_head', meltInto: 100, useForgeTag: false, useDurability: false },
    { name: 'chisel', meltInto: 100, useForgeTag: false, useDurability: true },
    { name: 'double_ingot', meltInto: 200, useForgeTag: false, useDurability: false },
    { name: 'double_sheet', meltInto: 400, useForgeTag: false, useDurability: false },
    { name: 'fish_hook', meltInto: 200, useForgeTag: false, useDurability: false },
    { name: 'fishing_rod', meltInto: 200, useForgeTag: false, useDurability: true },
    { name: 'greaves', meltInto: 600, useForgeTag: false, useDurability: true },
    { name: 'hammer', meltInto: 100, useForgeTag: false, useDurability: true },
    { name: 'hammer_head', meltInto: 100, useForgeTag: false, useDurability: false },
    { name: 'javelin', meltInto: 100, useForgeTag: false, useDurability: true },
    { name: 'javelin_head', meltInto: 100, useForgeTag: false, useDurability: false },
    { name: 'hoe', meltInto: 100, useForgeTag: false, useDurability: true },
    { name: 'hoe_head', meltInto: 100, useForgeTag: false, useDurability: false },
    { name: 'ingot', meltInto: 100, useForgeTag: true, useDurability: false },
    { name: 'helmet', meltInto: 600, useForgeTag: false, useDurability: true },
    { name: 'knife', meltInto: 100, useForgeTag: false, useDurability: true },
    { name: 'knife_blade', meltInto: 100, useForgeTag: false, useDurability: false },
    { name: 'lamp', meltInto: 100, useForgeTag: false, useDurability: false },
    { name: 'mace', meltInto: 200, useForgeTag: false, useDurability: true },
    { name: 'mace_head', meltInto: 200, useForgeTag: false, useDurability: false },
    { name: 'pickaxe', meltInto: 100, useForgeTag: false, useDurability: true },
    { name: 'pickaxe_head', meltInto: 100, useForgeTag: false, useDurability: false },
    { name: 'propick', meltInto: 100, useForgeTag: false, useDurability: true },
    { name: 'propick_head', meltInto: 100, useForgeTag: false, useDurability: false },
    { name: 'rod', meltInto: 50, useForgeTag: false, useDurability: false },
    { name: 'saw', meltInto: 100, useForgeTag: false, useDurability: true },
    { name: 'saw_blade', meltInto: 100, useForgeTag: false, useDurability: false },
    { name: 'scythe', meltInto: 100, useForgeTag: false, useDurability: true },
    { name: 'scythe_blade', meltInto: 100, useForgeTag: false, useDurability: false },
    { name: 'shears', meltInto: 200, useForgeTag: false, useDurability: true },
    { name: 'sheet', meltInto: 200, useForgeTag: false, useDurability: false },
    { name: 'shield', meltInto: 400, useForgeTag: false, useDurability: true },
    { name: 'shovel', meltInto: 100, useForgeTag: false, useDurability: true },
    { name: 'shovel_head', meltInto: 100, useForgeTag: false, useDurability: false },
    { name: 'sword', meltInto: 200, useForgeTag: false, useDurability: true },
    { name: 'sword_blade', meltInto: 200, useForgeTag: false, useDurability: false },
    { name: 'trapdoor', meltInto: 200, useForgeTag: false, useDurability: false },
    { name: 'tuyere', meltInto: 400, useForgeTag: false, useDurability: true },
    { name: 'unfinished_boots', meltInto: 200, useForgeTag: false, useDurability: false },
    { name: 'unfinished_chestplate', meltInto: 400, useForgeTag: false, useDurability: false },
    { name: 'unfinished_greaves', meltInto: 400, useForgeTag: false, useDurability: false },
    { name: 'unfinished_helmet', meltInto: 400, useForgeTag: false, useDurability: false }
];
export const parts = allToolParts.filter(part => part.name.includes('ingot') || part.name.includes('sheet') || part.name == 'rod');
